# 1. Suppose we are analyzing clinical trial data. We have a patient's ID (integer), their prescribed drug name (string), and their dosage in milligrams (float). If we put all of this into a single NumPy array, what happens to the data types, and why does that ruin our ability to do math?
# When we combine an integer (patient ID), a string (drug name), and a float (dosage) into a single NumPy array, NumPy converts all elements to a common data type, usually a string (dtype='<U...') or object.
# Explanation:
# NumPy arrays are designed to store homogeneous data (all elements must have the same type). Since strings cannot be converted into numbers safely, NumPy promotes everything to a string type. As a result, numeric values like 50.0 become "50.0", and mathematical operations no longer work correctly. This ruins our ability to perform calculations because arithmetic operations require numeric data types, not strings.
#2. Imagine a machine learning dataset with 150 different features (columns). If you need to extract specifically the 'Blood Pressure' and 'Heart Rate' columns to feed into your model, how do you do that in NumPy without manually counting and memorizing their exact index numbers?
#NumPy arrays do not store column names, only positions. By maintaining a separate list of column names, we can look up the index using .index() instead of memorizing it. This makes the code more flexible and less error-prone, especially when working with large datasets.
#3. If we have a NumPy array of patient ages, but one patient declined to answer, we might use np.nan (Not a Number) as a placeholder. What happens if we try to calculate the average age using np.mean() on that array?
#np.nan represents a missing or undefined value. When NumPy computes the mean, any operation involving np.nan results in np.nan, causing the entire average to become invalid. To handle this properly, we use:
#4. You have one NumPy array containing patient demographics, and a completely separate array containing their chemotherapy regimens. How would you match them up perfectly based on a shared 'Patient ID' using just standard Python and NumPy?
#Each dataset contains a shared key (Patient ID). By sorting both arrays using this key, we align corresponding rows so that the same patient appears in the same position in both arrays. After alignment, we can combine the data safely. This ensures that each patient’s demographic data correctly matches their treatment data.
import pandas as pd
df=pd.read_csv('earthquake.csv')
print(df)